### ISSUE TITLE
code step 3 slide is incorrect

### ISSUE THREAD

**Issue by jeanettehead** [mike-north/pwa-fundamentals#42]
The text on this slide says to add the worker import to `App.jsx`.  However, based on [this commit](https://github.com/mike-north/pwa-fundamentals/commit/91d255fb068c4ebc6e74a8407a1cf0e39bd1c139) from the `femasters-3-complete` branch, this is wrong, and it should be added to `client/index.js`. ( I spent a few hours debugging why my web server wouldn't start when I had it added to `App.jsx`)

<img width="1034" alt="screen shot 2017-10-29 at 10 49 15 pm" src="https://user-images.githubusercontent.com/1103787/32155212-88c94be8-bcfb-11e7-9293-89e43b51a921.png">

(I attended Steve's talk at Develop Denver and finally got around to checking this out. Thanks for having it available 😀 )

**Comment by mike-north** [comment]
Thanks for catching this Jeanette. The worker can go in either file. I’ll rewrite the solution to match the slides, since it’s also recorded on video!

**Comment by mike-north** [comment]
new version of the solution has been pushed and the branches have been rebased!
