### ISSUE TITLE
Add This Workaround for `https` Certs on Windows 10

### ISSUE THREAD

**Issue by phil-lgr** [mike-north/pwa-fundamentals#43]
I spend an hour fighting with the certificates... when I discovered that page:

https://www.chromium.org/blink/serviceworker/service-worker-faq

solution is to start chrome with:

```
"C:\Program Files (x86)\Google\Chrome Beta\Application\chrome.exe" --allow-insecure-localhost https://localhost
```

Would highly recommend you suggest using this trick during development... playing with certs on Windows is not pretty... the flag allow me to use service worker, fetch, push notifications!

**Comment by phil-lgr** [comment]
BTW I am doing the lessons on Front End Master, watching the replay! 🔥

**Comment by mike-north** [comment]
Thanks for posting this. Were you able to make it through the whole course with this flag on? At the time @stevekinney and I taught this, we had some problems in the later exercises that required use of https. 

Thankfully you don't even need to start chrome up with a special flag anymore. You can just use the chrome flags UI to toggle the same setting --> chrome://flags/#allow-insecure-localhost

**Comment by phil-lgr** [comment]
Not sure, I ran the last completed demo as I was in a need of example rather than doing the tutorial. 😅 With the flag #allow-insecure-localhost I was getting notifications and proper registration of the sw. Not sure where it wouldn't work. :)
