### ISSUE TITLE
npm install Fails.

### ISSUE THREAD

**Issue by ShadyXV** [mike-north/pwa-fundamentals#48]
npm fails when its renaming a file inside node_modules.
I think its this files - /node_modules/concurrently/src/main.js.3376272737
I am running this on Bash in a windows 10.

**Comment by mike-north** [comment]
which npm and node versions are you using? Do you have a log file I can look at?

**Comment by mike-north** [comment]
Closing this as a duplicate of #47, since they are both "I can't get running on win10" issues.
