### ISSUE TITLE
How do I correctly set the Api endpoint for the Android simulator

### ISSUE THREAD

**Issue by amite** [mike-north/pwa-fundamentals#51]
On the android simulator, the data is not loaded because the endpoint it is trying to hit is `https://localhost:3100`, which as you indicated, does not work on the simulator.

<img width="537" alt="screen shot 2017-12-25 at 12 19 12 pm" src="https://user-images.githubusercontent.com/1308947/34334596-ddc7f9e8-e96d-11e7-9057-9016b4117ebd.png">

How do I fix this?

**Comment by mike-north** [comment]
You would have to figure out the IP address of your computer and use that

**Comment by amite** [comment]
Ok I just tried setting `API_ENDPOINT` to `https://27.4.47.162:3100/` which is the ip of my computer but then the api stopped working. This is probably not the way you want me to use this - am I right?

**Comment by amite** [comment]
Yeah starting the app with `API_ENDPOINT=https://{MY_IP_ADDRESS}:3100/  yarn start` worked
